# Generated by Django 5.2 on 2025-04-30 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("start_datetime", models.DateTimeField()),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("one time", "یک بار"),
                            ("every year", "هر سال"),
                            ("every month", "هر ماه"),
                            ("every 30 days", "هر ۳۰ روز"),
                            ("every 28 days", "هر ۲۸ روز"),
                            ("every 14 days", "هر ۱۴ روز"),
                            ("every week", "هر هفته"),
                            ("every 3 days", "هر ۳ روز"),
                            ("every 2 days", "هر ۲ روز"),
                            ("every day", "هر روز"),
                            ("every 12 hours", "هر ۱۲ ساعت"),
                            ("every 8 hours", "هر ۸ ساعت"),
                            ("every 6 hours", "هر ۶ ساعت"),
                            ("every 4 hours", "هر ۴ ساعت"),
                            ("every 180 days", "هر ۱۸۰ روز"),
                            ("every 120 days", "هر ۱۲۰ روز"),
                            ("every 90 days", "هر ۹۰ روز"),
                            ("every 60 days", "هر ۶۰ روز"),
                            ("every 21 days", "هر ۲۱ روز"),
                            ("every 15 days", "هر ۱۵ روز"),
                            ("every 10 days", "هر ۱۰ روز"),
                            ("every 5 days", "هر ۵ روز"),
                            ("every 4 days", "هر ۴ روز"),
                            ("every 10 years", "هر ۱۰ سال"),
                            ("every 7 years", "هر ۷ سال"),
                            ("every 5 years", "هر ۵ سال"),
                            ("every 4 years", "هر ۴ سال"),
                            ("every 3 years", "هر ۳ سال"),
                            ("every 2 years", "هر ۲ سال"),
                        ],
                        max_length=64,
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="فعال")),
                ("email", models.BooleanField(default=True, verbose_name="ایمیل")),
                ("telegram", models.BooleanField(default=True, verbose_name="تلگرام")),
                ("sms", models.BooleanField(default=False, verbose_name="اس ام اس")),
                (
                    "notification",
                    models.BooleanField(default=False, verbose_name="نوتیفیکیشن"),
                ),
                ("whatsapp", models.BooleanField(default=False, verbose_name="واتساپ")),
                ("eta", models.BooleanField(default=False, verbose_name="ایتا")),
                ("bale", models.BooleanField(default=False, verbose_name="بله")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
